# Generated by Django 4.1.5 on 2023-02-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('text', models.TextField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('urgency', models.CharField(choices=[('не срочно', 'Не срочно'), ('срочно', 'Срочно'), ('очень срочно', 'Очень срочно')], default='не срочно', max_length=20)),
                ('file', models.FileField(upload_to='cars')),
            ],
        ),
    ]
