# Generated by Django 4.1.5 on 2023-02-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact', verbose_name='Файл')),
                ('Application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.application')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
