# Generated by Django 4.1.5 on 2023-02-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_remove_application_file_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='Application',
            new_name='application',
        ),
    ]
