# Generated by Django 4.1.5 on 2023-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0003_rename_application_files_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
    ]
