version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      -  ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=user_18
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_18
volumes:
  postgres_data: